# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'PPListDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Introspect'
  pod 'SDWebImageSwiftUI'
  pod 'lottie-ios'
  pod 'SnapKit', '~> 5.6.0'
  pod 'MJRefresh', '~> 3.5.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # xcode14.3 To fix this issue, you must ensure that the iOS Deployment Target of your pods is 11.0 https://developer.apple.com/forums/thread/728021
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
